[package]
name = "nscope-nodejs"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nscope = "1.0.0-dev.3"

[dependencies.neon]
version = "0.10.1"
default-features = false
features = ["napi-6"]
