name: nScope Packaging

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "50 0 1,15 * *"
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - os: ubuntu-latest
            target_architecture: x64
            executable_path: xvfb-run out/nScope-linux-x64/nScope
            artifact_path: out/make/deb/x64/nscope_*.deb
            artifact_name: 'Linux Package (deb)'
          - os: macos-latest
            target_architecture: universal
            executable_path: out/nScope-darwin-universal/nScope.app/Contents/MacOS/nScope
            artifact_path: 'out/make/nScope Installer.dmg'
            artifact_name: 'macOS Installer (dmg)'
          - os: windows-latest
            target_architecture: x64
            executable_path: out/nScope-win32-x64/nScope.exe
            artifact_path: 'out/make/squirrel.windows/x64/*'
            artifact_name: 'Windows Installer (exe)'
    name: ${{ matrix.target_architecture }} on ${{ matrix.os }}
    steps:
      - name: Install Rust Toolchains
        if: matrix.os == 'macos-latest'
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Install libusb
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libusb-1.0-0-dev libudev-dev
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install NPM Dependencies
        run: npm ci
      - name: Setup Digicert Keylocker
        if: matrix.os =='windows-latest'
        uses: digicert/ssm-code-signing@v1.0.0
      - name: Build nScope
        run: npm run build
      - name: Setup MacOS certs
        if: matrix.os == 'macos-latest'
        run: ./.github/add-osx-cert.sh
        env:
          CERTIFICATE_OSX_APPLICATION: ${{ secrets.MACOS_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: Setup Windows certs
        if: matrix.os =='windows-latest'
        run: |
          echo "${{ secrets.DIGICERT_CLIENT_CERT_FILE }}" | base64 --decode > /d/digicert_sm_cert.p12
          echo "${{ secrets.WINDOWS_SIGNING_CERT }}" | base64 --decode > /d/signing_cert.crt
        shell: bash
      - name: Package
        run: npm run make -- --arch ${{ matrix.target_architecture }}
        env:
          DEBUG: "electron-packager,electron-windows-installer:main"
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          SM_HOST: ${{ secrets.DIGICERT_HOST }}
          SM_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.DIGICERT_CLIENT_CERT_PASSWORD }}
          SM_CLIENT_CERT_FILE: D:\\digicert_sm_cert.p12
          CODE_SIGNING_CERT_FILE: D:\\signing_cert.crt
      - name: Smoke Test
        run: ${{ matrix.executable_path }}
        env:
          NSCOPE_SMOKE_TEST: 1
      - name: Archive the distributable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
      - name: Create Update Zips for macOS
        if: matrix.os == 'macos-latest'
        working-directory: ./out/make/zip/darwin/universal
        run: |
          f=$(echo nScope-darwin-universal-*.zip); cp "$f" $(sed 's:universal:x64:' <<< "$f")
          f=$(echo nScope-darwin-universal-*.zip); cp "$f" $(sed 's:universal:arm64:' <<< "$f")
      - name: Archive the updaters
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: macOS update packages (zip)
          path: |
            ./out/make/zip/darwin/universal/*x64*.zip
            ./out/make/zip/darwin/universal/*arm64*.zip
      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        env:
          DEBUG: "electron-packager,electron-windows-installer:main"
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          SM_HOST: ${{ secrets.DIGICERT_HOST }}
          SM_API_KEY: ${{ secrets.DIGICERT_API_KEY }}
          SM_CLIENT_CERT_PASSWORD: ${{ secrets.DIGICERT_CLIENT_CERT_PASSWORD }}
          SM_CLIENT_CERT_FILE: D:\\digicert_sm_cert.p12
          CODE_SIGNING_CERT_FILE: D:\\signing_cert.crt
